"""
FILE: engine/core/naming_utils.py
ROLE: Cross-platform safe naming for files, directories, and DB keys.

DESCRIPTION:
All file and folder names generated by the app pass through NamingUtils before
hitting the filesystem. This ensures:
  - No Windows-illegal characters (<>:"/\\|?*)
  - No leading/trailing spaces or dots (Windows edge cases)
  - Predictable, consistent filenames across Linux, macOS, and Windows
  - Spaces → underscores for filenames (prevents shell quoting issues)

IMPORTANT: These utilities operate on RAW strings (names), not DB keys or
absolute paths. For path handling, see engine/data/api/json_db.py.
"""
import re
import os


class NamingUtils:
    """Central utility for validating, sanitizing, and formatting strings and file paths."""

    # Characters illegal on Windows filesystems (and confusing on Linux too)
    _INVALID_FILENAME_CHARS = re.compile(r'[<>:"/\\|?*\x00-\x1f]')
    # Characters illegal specifically as the first/last char on Windows
    _STRIP_EDGE_CHARS = re.compile(r'^[\s.]+|[\s.]+$')

    @classmethod
    def sanitize_filename(cls, filename: str, replacement: str = "_") -> str:
        """
        Produces a cross-OS safe filename component (no slashes, no illegal chars).
        Spaces are preserved as-is since they're legal on all OS. Use
        sanitize_filename_strict() if you need space-free names.

        Valid:   'my_file.json'  -> 'my_file.json'
        Invalid: 'Test:Project?' -> 'Test_Project_'
        """
        if not filename:
            return "unnamed"
        result = cls._INVALID_FILENAME_CHARS.sub(replacement, str(filename))
        # Strip leading/trailing dots and spaces (Windows rejects these)
        result = cls._STRIP_EDGE_CHARS.sub("", result)
        return result or "unnamed"

    @classmethod
    def sanitize_filename_strict(cls, filename: str) -> str:
        """
        Produces a maximally safe filename: no spaces, no illegal chars.
        Spaces → underscores. Use this for DB keys and generated IDs.

        'New Scenario' -> 'New_Scenario'
        'Test:Map?'    -> 'Test_Map_'
        """
        if not filename:
            return "unnamed"
        result = cls._INVALID_FILENAME_CHARS.sub("_", str(filename))
        result = result.replace(" ", "_")
        result = cls._STRIP_EDGE_CHARS.sub("", result)
        return result or "unnamed"

    @classmethod
    def sanitize_path(cls, path_string: str) -> str:
        r"""
        Sanitizes a path string while preserving directory separators (/ and \).
        Each component is individually sanitized. Spaces in path components are
        preserved since they're legal in directory names on all platforms.
        """
        if not path_string:
            return ""

        # Normalize to forward slashes, then split into components
        parts = path_string.replace("\\", "/").split("/")

        sanitized_parts = []
        for i, part in enumerate(parts):
            # Allow Windows drive letter at index 0 (e.g. C:)
            if i == 0 and len(part) == 2 and part[1] == ':':
                sanitized_parts.append(part)
            # Allow empty string at index 0 (Linux absolute path root '/')
            elif i == 0 and part == "":
                sanitized_parts.append("")
            else:
                sanitized_parts.append(cls.sanitize_filename(part))

        return "/".join(sanitized_parts)

    @classmethod
    def generate_id(cls, name: str) -> str:
        """
        Generates a lowercase, underscore-separated ID string safe for use as
        a DB key, file stem, or dictionary key.

        'Main Battle Tank' -> 'main_battle_tank'
        'New Scenario'     -> 'new_scenario'
        """
        if not name:
            return "unnamed_entity"
        return cls.sanitize_filename_strict(name.lower())
